* ՔՆՆԱԽՈՍՈՒԹՅՈՒՆ ՄԵԹՈԴԻ ՄԱՍԻՆ
ԲԱՆԱԿԱՆՈՒԹՅԱՆԸ ԼԱՎ ՈՒՂՂՈՒԹՅՈՒՆ ՏԱԼՈՒ
և ԳԻՏՈՒԹՅՈՒՆՆԵՐԻ ՄԵՋ ՃՇՄԱՐՏՈՒԹՅՈՒՆ ՈՐՈՆԵԼՈՒ ՀԱՄԱՐ

Եթե այս քննախոսությունը միանգամից ենթերցելու
համար շատ երկար թվա, ապա կարելի այն բաժանել վեց մասի.
- առաջին մասում գտնվում են զանազան խորհրդածություններ
  գիտությունների վերաբերյալ.
- երկրորդում՝ հեղինակի ուսումնասիրած մեթոդի գլխավոր կանոննը.
- երրորդում՝ բարոյականության մի քանի կանոններ, որ հեղինակը հանել
  այդ մեթոդից.
- չորրորդում՝ այն փաստարկները, որոնցով նա ապացուցում է իր մետաֆիզիկայի
  հիմքը կազմող՝ աստծո և մարդկային հոգու գոյությունը.
- հինգերորդում՝ ֆիզիկական հարցերի կարգը, որ նա ուսումնասիրել է, և 
  մասնավորապես սրտի շարժման և բժշկականության պատկանող մի քանի 
  դժվարությունների բացատրությունը, նաև այն տարբերությունը, որ կա մեր 
  հոգու և կենդանիների հոգու մեջ և, 
- վերջապես, հեղինակը վերջին մասում մատնանշում է այն ինչը, նրա կարծիքով, 
  անհրաժեշտ է բնության հետազոտության մեջ ավելի, քան կատարվել ձ մինչև այժմ, 
  առաջ գնալու համար, ինչպես նաև այս աշխատությունը գրելու շարժառիթները:

* Մասն  առաջին
ԿՇՌԱԴԱՏՈՒՄՆԵՐ ԳԻՏՈՒԹՅՈՒՆՆԵՐԻ ՄԱՍԻՆ
  
** Հանճարեղ տողեր խելքի բաշխվածության մասին                   :originaltext:
   Խելքը աշխարհում ամենաարդարացի բաժանված բանն է,
   որովհետև ամեն մարդ մտածում է, թե ինքն այնքան է օժտված
   նրանով, որ անգամ այնպիսինները, որոնք ուրիշ ամեն բանի մեջ 
   խիստ դժվարահաճ են, այստեղ սովորություն չունեն այլևս՝ իրենց 
   ունեցածից ավելին ցանկանալու: 
*** 
** 
   Անշուշտ, ճշմարտանման չի կարող լինել, թե այդ հարցում բոլորն էլ 
   մոլորված են. ավելի շուտ, սա վկայում է, որ լավ դատելու և ճիշտը սխալից 
   ջոկելու կարողությունը - ինչ որ իսկապես խելք կամ բանականություն է 
   կոչվում - ի բնե հավասար է բոլոր մարդկանց մեջ: Այդպես էլ, մեր կարծիքների 
   այլազանությունը նրանից չէ, որ ովամք ավելի խելացի են քան ուրիշները, այլ 
   միայն նրանից, որ մենք ուղղում ենք մեր մտքերը տարբեր ճանապարհներով և 
   քննության ենք առնում ո՛չ միևնույն բաները: Ըստ որում, բավական չէ, որ մարդու
   միտքը լավ լինի, գլխավորը՝ նրա լավ գործածությունն է: Ամենամեծ մտքերն ընդոնակ
   են ամենամեծ մոլորւթյունների, ինչպես և ամենամեծ առաքինությունների. և շատ դանդաղ
   քայլողները, եթե հետևեն միշտ ուղիղ ճամփին, կարող են շատ ավելի առաջ գնալ, 
   քան նրանք, որոնք վազում են և ուղիղ ճամփից հեռանում:
*** Մտածողության մեթոդը և մտածողության առարկան կարծիքների այլազանության հիմնական պատճառ
   - ուղղում ենք մեր մտքերը տարբեր ճանապարհներով
     խոսքը մեթոդի մասին է
   - քննության ենք առնում ո՛չ միևնույն բաները
     մտածողության առարկայի ընտրության հարցն է
   - գլխավորը՝ նրա լավ գործածությունն է
     ունենալ մեթոդ

** Ոգու և բանականության մասին
  :PAGE: 40
   Ես ինքս երբեք հավակնություն չեմ ունեցել, թե իմ ոգին մի որևէ բանով ավելի կատարյալ է, 
   քան սովորական մարդունը, և նույնիսկ հաճախ ես ցանկացել էմ ունենալ մտքի նույնքան 
   արագություն, կամ նույնքան հստակ ու պարզ երևակայություն, կամ նույնքան ընդարձակ
   ու կենդանի հիշողություն, որքան շատ ուրիշները: Սրանցից դուրս չեմ կարող ցույց տալ որևէ այլ 
   հատկություն, որ ծառայեր ոգու կատարելությանը. ինչ վերաբերում է բանականությանը կամ մտքին,
   ապա դա լինելով միակ բանը, որ մեզ մարդ է դարձնում և կենդանիներից տարբերում, ապա ես
   ուզում եմ հավատալ, որ այն լիակատար չափով հատուկ է յուրաքանչյուրին: Այստեղ պետք
   է հետևել այն ընդհանուր կարծիքին, որ հայտնել են փիլիսոփաները, թե ավելին ու պակասը 
   պատահական հատկանիշների (accidents) մեջ են և ոչ  բնավ միևնույն տեսակի անհատների 
   ձևերի կամ բնույթի մեջ:

***  
    - Ոգու կատարելություն ցույց տվող հատկություններ
      * մտքի արագություն
      * հստակ և պարզ երևակայություն
      * ընդարձակ կենդանի հիշողություն
    - Բանականություն կամ միտք
      * միակ բան է որ մարդ է դարձնում և կենդանիներից տարբերում
      * լիակատար չափով հատուկ է յուրաքանչյուրին
      * ավելին կամ պակասը պատահական հատկանիշների մեջ են
       
** մարդկային լավ և կարևոր զբաղմունք, գիտելիքները աստիճանաբար ընդարձակել 
   :PAGE: 40, 41
   Բայց չեմ դժվարանում ասել, որ շատ հաճախ, սկսած երիտասարդությունիցս, ես գնացել եմ
   այնպիսի ուղիներով, որոնք ինձ բերեցին այն խորհրդածություններին և կանոններին, որոնց հիման
   վրա ես ինձ համար մի մեթոդ մշակեցի, որով ինձ թվում է, թե ես գտել եմ մի միջոց՝ իմ գիտելիքները 
   աստիճանաբար ընդարձակելու, և քիչ-քիչ հասցնելու այն ամենաբարձր կետին, որին թույլ կարող են տալ
   հասնելու մտքիս միջակությունը և կյանքիս կարճատևուլյունը: Այդ մեթոդի օգնությամբ ես արդեն հասել եմ
   որոշակի արդյունքների չնայած նրան, որ ինքս ինձ դատելիս ես միշտ ջանում եմ ավելի շուտ հակվել դեպի
   շգուշավորությունը, քան դեպի հավակնոտությունը: Փիլիսոփայի աչքով դիտելով շատ շատերի գործերն 
   ու ձեռնարկումները, ես գրեթե ոչինչ չեմ գտնում դրանց, մեջ, որ ինձ ունայն և անօգուտ չթվար, բայց ես 
   բարձրագույն բավականություն եմ զգում, երբ կարծում եմ, թե ճշմարտության որոնման մեջ որոշ առաջադիմություն
   եմ կատարել ու նման հույսեր եմ տածում ապագայի նկատմամբ ևս, և համարձակվում եմ կարծել, որ եթե 
   մարդկային, զուտ մարդկային, զբաղմունքների մեջ կա մեկը, որ հատկապես լավ և կարևոր է, դա հենց 
   իմ ընտրածն է:

*** 
    - կյանքի ուղղիներ - խորհրդածություններ և կանոններ - մեթոդ
    - մեթոդ, միջոց՝ գիտելիքները աստիճանաբար ընդարձակելու, և քիչ-քիչ հասցնելու այն ամենաբարձր կետին
    - մեթոդի օգնությամբ ես արդեն հասել եմ որոշակի արդյունքների
    - մարդկային, զբաղմունքների մեջ կա մեկը, որ հատկապես լավ և կարևոր է, դա գիտելիքների 
      աստիճանաբար ընդարձակելու, և քիչ-քիչ հասցնելու այն ամենաբարձր կետին զբաղմունքն է:

** 
   
